# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  # makes classes in src/AppBundle available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  AppBundle\:
    resource: '../../src/AppBundle/*'
    # you can exclude directories or files
    # but if a service is unused, it's removed anyway
    exclude: '../../src/AppBundle/{Entity,Repository}'

  AppBundle\Controller\:
      resource: '../../src/AppBundle/Controller/*'
      public: true 
      tags: ['controller.service_arguments']
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
