app:
    resource: "../src/Controller/"
    type:     annotation
homepage:
    path: /
    defaults:
        _controller: App\Controller\DefaultController::indexAction
login:
    path:     /login
    defaults: { _controller: App\Controller\SecurityController::loginAction }

user_registration:
    path:     /users/create
    defaults: { _controller: App\Controller\UserController:createAction }   