app:
    resource: "../src/Controller/"
    type:     annotation
login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

user_registration:
    path:     /users/create
    defaults: { _controller: AppBundle:User:user_create }   